export * from './my-computer';
export * from './setting';
export * from './terminal';
export * from './camera';
export * from './microsoft-store';
export * from './my-computer';
export * from './folder';
export * from './edge';
export * from './notepad';
